#!/bin/bash

sudo yum update rpm -y; 
sudo update -y
sudo yum install git -y
git config --global user.name "noorydean"
git config --global user.email "noorydean@gmail.com"


git clone https://git@github.com:noorydean/scriptclass.git /root/scriptclass || echo "This is expected"
